name: Terraform Deploy

on:
  workflow_run:
    workflows: ["Docker Image CI/CD"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Short Commit Hash
        run: echo "TC_IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-west-2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./devops/terraform
        run: |
          export TF_LOG=DEBUG
          terraform init

      - name: Terraform Apply
        working-directory: ./devops/terraform
        run: |
          terraform apply -auto-approve \
            -var "key_mercado_pago=${{ secrets.KEY_MERCADO_PAGO }}" \
            -var "db_password=${{ secrets.TF_VAR_DB_PASSWORD }}" \
            -var "db_username=${{ secrets.TF_VAR_DB_USER }}" \
            -var "db_name=${{ secrets.TF_VAR_DB_NAME }}" \
            -var "tc_image_tag=${{ env.TC_IMAGE_TAG }}"

